//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbitriosMov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArbitriosMov()
        {
            this.CruceOrden = new HashSet<CruceOrden>();
            this.Ordenes = new HashSet<Ordenes>();
        }
    
        public int IDArbitrioMov { get; set; }
        public int IDEspacio { get; set; }
        public int IDDepto { get; set; }
        public string Arbitrio { get; set; }
        public string NaturalezaArbitrio { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public bool EsCorriente { get; set; }
        public bool TieneAdcional { get; set; }
        public bool TieneRecargos { get; set; }
        public bool EsRezago { get; set; }
        public bool TieneAdicionalRezago { get; set; }
        public bool TieneRecargosRezago { get; set; }
        public bool TieneMulta { get; set; }
        public bool TieneHonorarios { get; set; }
        public bool TieneEjecucion { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Espacios Espacios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruceOrden> CruceOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes> Ordenes { get; set; }
    }
}
