//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratos()
        {
            this.Movimientos = new HashSet<Movimientos>();
        }
    
        public int IDContrato { get; set; }
        public int IDPersona { get; set; }
        public int IDLocal { get; set; }
        public int IDGiro { get; set; }
        public int IDTipoOcupacionUso { get; set; }
        public string NombreComercial { get; set; }
        public bool EsContrato { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaVencim { get; set; }
        public string NombreFiador { get; set; }
        public Nullable<int> DiaFijoPago { get; set; }
        public Nullable<int> NumYearsVigencia { get; set; }
        public int IDUser { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Giros Giros { get; set; }
        public virtual Locales Locales { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual TipoOcupacionUso TipoOcupacionUso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}
