//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruceOrden
    {
        public int ID { get; set; }
        public int IDEspacio { get; set; }
        public int IDTipoMov { get; set; }
        public int IDArbitrioMov { get; set; }
    
        public virtual ArbitriosMov ArbitriosMov { get; set; }
        public virtual Espacios Espacios { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
}
