//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locales()
        {
            this.Contratos = new HashSet<Contratos>();
        }
    
        public int IDLocal { get; set; }
        public int IDEspacio { get; set; }
        public Nullable<int> IDNave { get; set; }
        public Nullable<int> IDSeccion { get; set; }
        public int IDTipoCuota { get; set; }
        public bool Ocupado { get; set; }
        public string Local { get; set; }
        public float MFrente { get; set; }
        public float MFondo { get; set; }
        public float MCuadTotales { get; set; }
        public Nullable<int> NumLocParaCobro { get; set; }
        public float ImporteRenta { get; set; }
        public Nullable<bool> PorMetraje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual Espacios Espacios { get; set; }
        public virtual Naves Naves { get; set; }
        public virtual Secciones Secciones { get; set; }
        public virtual TipoCuotas TipoCuotas { get; set; }
    }
}
