//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int IDMovimiento { get; set; }
        public int IDContrato { get; set; }
        public Nullable<int> IDPermiso { get; set; }
        public int IDTipoMovimiento { get; set; }
        public int IDUser { get; set; }
        public Nullable<int> IDOrden { get; set; }
        public float ImporteTotal { get; set; }
        public string FolioRecibo { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<float> Corriente { get; set; }
        public Nullable<float> Adicional { get; set; }
        public Nullable<float> Recargos { get; set; }
        public Nullable<float> Rezago { get; set; }
        public Nullable<float> AdicionalRezago { get; set; }
        public Nullable<float> RecargoRezago { get; set; }
        public Nullable<float> Multa { get; set; }
        public Nullable<float> Honorarios { get; set; }
        public Nullable<float> Ejecucion { get; set; }
        public Nullable<float> Redondeo { get; set; }
        public string Observaciones { get; set; }
        public string Estatus { get; set; }
        public string Periodo { get; set; }
    
        public virtual Contratos Contratos { get; set; }
        public virtual Ordenes Ordenes { get; set; }
        public virtual Permisos Permisos { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual Users Users { get; set; }
    }
}
