//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OccupancyEntities : DbContext
    {
        public OccupancyEntities()
            : base("name=OccupancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArbitriosMov> ArbitriosMov { get; set; }
        public virtual DbSet<Contratos> Contratos { get; set; }
        public virtual DbSet<CruceOrden> CruceOrden { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Espacios> Espacios { get; set; }
        public virtual DbSet<GiroInformal> GiroInformal { get; set; }
        public virtual DbSet<Giros> Giros { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Movimientos> Movimientos { get; set; }
        public virtual DbSet<Naves> Naves { get; set; }
        public virtual DbSet<Ordenes> Ordenes { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
        public virtual DbSet<TipoCuotas> TipoCuotas { get; set; }
        public virtual DbSet<TipoMedioInformal> TipoMedioInformal { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual DbSet<TipoOcupacionUso> TipoOcupacionUso { get; set; }
        public virtual DbSet<TipoPermisoInformal> TipoPermisoInformal { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
    }
}
