//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.Movimientos = new HashSet<Movimientos>();
        }
    
        public int IDOrden { get; set; }
        public int IDUser { get; set; }
        public int IDArbitrioMov { get; set; }
        public int IDDepto { get; set; }
        public string FolioRecibo { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public float ImporteTotal { get; set; }
        public float Corriente { get; set; }
        public float Adicional { get; set; }
        public float Recargo { get; set; }
        public float Rezago { get; set; }
        public float AdicionalRezago { get; set; }
        public float RecargoRezago { get; set; }
        public float Multa { get; set; }
        public float Honorarios { get; set; }
        public float Ejecucion { get; set; }
        public Nullable<float> Redondeo { get; set; }
        public string Observaciones { get; set; }
        public string Estatus { get; set; }
    
        public virtual ArbitriosMov ArbitriosMov { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
        public virtual Users Users { get; set; }
    }
}
