//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int IDParametro { get; set; }
        public int Year { get; set; }
        public Nullable<double> UMAProrrateada { get; set; }
        public Nullable<System.DateTime> FechaLimiteProrrateada { get; set; }
        public Nullable<double> UMANormal { get; set; }
        public Nullable<System.DateTime> FechaLimiteNormal { get; set; }
    }
}
