//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permisos()
        {
            this.Movimientos = new HashSet<Movimientos>();
            this.Vendedores = new HashSet<Vendedores>();
        }
    
        public int IDPermiso { get; set; }
        public int IDPersona { get; set; }
        public int IDEspacio { get; set; }
        public int IDTipoOcupacionUso { get; set; }
        public int IDGiroInformal { get; set; }
        public Nullable<int> IDTipoMedioInformal { get; set; }
        public int IDTipoPermisoInformal { get; set; }
        public Nullable<int> NombreComercial { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> DiaFijoPago { get; set; }
        public System.DateTime FechaPermiso { get; set; }
        public Nullable<System.DateTime> FechaHrInicio { get; set; }
        public Nullable<System.DateTime> FechaHrFin { get; set; }
        public int IDUser { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Espacios Espacios { get; set; }
        public virtual GiroInformal GiroInformal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
        public virtual Permisos Permisos1 { get; set; }
        public virtual Permisos Permisos2 { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual TipoMedioInformal TipoMedioInformal { get; set; }
        public virtual TipoOcupacionUso TipoOcupacionUso { get; set; }
        public virtual TipoPermisoInformal TipoPermisoInformal { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendedores> Vendedores { get; set; }
    }
}
