//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCuotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoCuotas()
        {
            this.Locales = new HashSet<Locales>();
        }
    
        public int IDTipoCuota { get; set; }
        public int IDEspacio { get; set; }
        public int IDNave { get; set; }
        public string TipoCuota { get; set; }
        public float ImporteRenta { get; set; }
        public Nullable<float> PorcentajeAdicional { get; set; }
        public Nullable<float> FactorAdicional { get; set; }
        public float FactorUMADiario { get; set; }
        public Nullable<float> FactorUMAMensual { get; set; }
        public Nullable<float> FactorUMARecargoDiario { get; set; }
        public Nullable<float> FactorUMARecargoMensual { get; set; }
        public Nullable<float> PorcentajeRecargoMensual { get; set; }
        public int Year { get; set; }
        public System.DateTime FechaAplicaInicial { get; set; }
        public System.DateTime FechaAplicaFinal { get; set; }
        public Nullable<bool> PorMetraje { get; set; }
    
        public virtual Espacios Espacios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locales> Locales { get; set; }
        public virtual Naves Naves { get; set; }
    }
}
